version: '3'
services:
  mkdocs:
    image: jssdocente/mkdocs-daw
    build:
      context: ./.docker
      dockerfile: dockerfile
      
    container_name: Mkdocs-pg2526
    ports:
      - "8007:8000"
    volumes:
      - ./:/docs

    command: serve --dev-addr 0.0.0.0:8000 --dirtyreload
    stdin_open: true
    tty: true